### ISSUE TITLE
Why do we use option instead of results everywhere???

### ISSUE THREAD

**Issue by luke-bhan** [ayazhafiz/slide#110]
For example, in the function rules, why are we using option for modulo or exponentiation when it should be a result right? Also, we always return some so I don't understand the options here. I should've said something during code review, my fault.

**Comment by ayazhafiz** [comment]
Why should it be a result?

**Comment by ayazhafiz** [comment]
For example, in gcd_heu_zz it makes sense to have an option -- either we succeed or we don't, and there's no special "error" for when we fail.

For a rule, a rule can either succeed or it can't because it wasn't able to match anything on the expression. You could pass a result instead, but then the result would always look like `Result<Expr, "Failed to match rule with expression">`. I'm not sure that this is useful?

**Comment by luke-bhan** [comment]
Ah I see. Ok this is fine.
