### ISSUE TITLE
Fix multiple unary operator issue

### ISSUE THREAD

**Issue by luke-bhan** [ayazhafiz/slide#49]
Fix an issue such that ++++++5 throws an error message.

**Comment by luke-bhan** [comment]
ok I played around this this on wolfram alpha. First, wolframp alpha is broken, try
+-++--5 and you'll get -6! Second, they allow operators like this inclining me to think we should as well because how are we gonna handle things like 5 + - 3? or do we want an error.

**Comment by luke-bhan** [comment]
@ayazhafiz

**Comment by ayazhafiz** [comment]
I think wolframalpha is treating `++5` as `6`, which leads to `-6`. I agree, I don't think this is the write way to do it though.

**Comment by ayazhafiz** [comment]
Can you elaborate on what you mean by handling things like `5 + - 3`? We already do, it's `(5 + -(3))`.

**Comment by luke-bhan** [comment]
yes, but I am saying if we remove the ability to have add/sub operators consecutively, we will have to manually handle cases like this? Or do you think we should just remove the ability to have more than 2. Also, fuck you're definitely write about WA.

**Comment by ayazhafiz** [comment]
Oh, I think we should still handle cases like this. But what would be cool is if you could emit a parser error for an expression like `+++5` saying that it's trivially reducable to `5`.

**Comment by luke-bhan** [comment]
Also, wait wolfram is wrong in that --5 doesn't reduce while ++5 increases. SMH. Ok, I think we can.

**Comment by ayazhafiz** [comment]
Wolfram may not handle this in the way we expect because it parses
expressions in a variety of contexts. In this context we may perceive a
math expression, but who knows what WA is seeing -- it may be a computation
expression to it.

**Comment by ayazhafiz** [comment]
Also, let's emit a `warning` or `hint` rather than an error.

**Comment by luke-bhan** [comment]
I am finding the typing for parsing incredible confusing right now. When we are calling self.exp_term(), we return a Rc<Self::Expr> which is a Parser::Expr. How do I get the unary node out of this.

**Comment by ayazhafiz** [comment]
You have to pattern match against the expression to figure out what kind of expression it is.

**Comment by luke-bhan** [comment]
you can't just pattern match with it though is what I am struggling with.

**Comment by ayazhafiz** [comment]
Yes, because the type of Self::Expr isn't concrete. You'll have to specialize it across the parser implementations. Here's an example:https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=49ce76c0fc9b3eeeec9e3e2a4d262f4b

**Comment by luke-bhan** [comment]
this is a good first issue @timothycobrien if you want to do it. I think the issue is in the parser evaluations, but have not dug super deep recently

**Comment by timothycobrien** [comment]
Yea sounds good. I'm familiar with this kind of stuff from grinding on assignment 8 in ISD a year and a half ago haha

**Comment by ayazhafiz** [comment]
btw, I don't think we should error on this, maybe emit a hint that's like

```
++++5
^^^^^ Hint: this is trivially reducible to +5
```

**Comment by ayazhafiz** [comment]
@luke-bhan @timothycobrien fixing this is trickier than I thought, could I get your insight on this?

To implement this we need to record spans of expressions during parsing and then have a second pass (let's call it `lint`) that emits warnings for this behavior.

Currently the parser eliminates common subexpressions by returning a common pointer for expressions with the same value. So if we parser `1 + 1`, the expression for `1` is pointing at the same underlying value. This makes later optimizations efficient for obvious reasons.

Anyway, it's clear that we can't map the underlying expression to a span because then we would have false positives (i.e. in the example above, both `1`s would have the same spans but this is absurd). My next idea was okay, we can just map it to the container that holds the expression (in this case, an `Rc` that holds a pointer to the underlying expression). But this doesn't work either, because the `Rc` lives in the stack (even though its underlying pointer doesn't) so as soon we move the Rc to a different location its memory address changes, and any mapping of the Rc to its span becomes invalidated.

As of now, I see a few options:

1. don't perform subexpression elimination until after parsing, as another pass
2. pass the Rc holding the expression as a pointer itself (so each expression is actually an `Rc<Rc<Expr>>`)
3. create some kind of wrapper that stores a `Span` and `Rc<Expr>` together in the parsing phase, and drops the `Span` part afterward.

(1) or (3) seem the most reasonable to me. Do you have any ideas or suggestions?

**Comment by ayazhafiz** [comment]
Or maybe we should just save the span on the grammar.

**Comment by luke-bhan** [comment]
@ayazhafiz we defintely shouldnot do 2. I think the span is the best method. Additionally, we could just handle it so that if the parser see two operators next to each other it always emits a warning there. It would warn stuff like 3 + -2 = 1 but I think this is ok. What do you think about that

**Comment by ayazhafiz** [comment]
I think that's good. I'm thinking of making a grammar that stores the `Span` and `Expression` together, and after the parsing/lint  phase we can have a quick pass that drops the span into a raw `Expression`. Does this sound good?

**Comment by luke-bhan** [comment]
yes. Although I think its not neccessary for this issue but ultimately better long term

**Comment by timothycobrien** [comment]
What's wrong with the first approach?

**Comment by luke-bhan** [comment]
I don't think anything, I think you need to make a second pass no matter what. I think @ayazhafiz is just going to add a span so that we have a framework for easily making that pass for other errors if I'm not mistaken @ayazhafiz

**Comment by ayazhafiz** [comment]
yep

**Comment by ayazhafiz** [comment]
this is really way harder than I expected

**Comment by ayazhafiz** [comment]
I can't see a good way to do this without making it really complicated or having a lot of duplication

**Comment by ayazhafiz** [comment]
What if we just don't implement it?

**Comment by ayazhafiz** [comment]
@luke-bhan @timothycobrien

**Comment by ayazhafiz** [comment]
Basically the issue I have is that we need to add another field to the struct, so we need to duplicate all of the expression code and then the parser becomes way more complicated because we're throwing around spans everywhere, and it doesn't work well with a lot of our `From` impls so all of that would have to be rewritten.

**Comment by ayazhafiz** [comment]
on the other hand we will have to eventually do this so I'm not opposed to it. but it will be a very big change so i'd rather do it after 0.1 since there's like 2 issues left for that

**Comment by ayazhafiz** [comment]
lmk what you think

**Comment by timothycobrien** [comment]
Yea just stick it on the backlog imo

**Comment by ayazhafiz** [comment]
aight bet imma close this and open a new issue explaining how this should be done
